### ISSUE TITLE
Support version

### ISSUE THREAD

**Issue by amirgee007** [solvercircle/laravel-banner-carousel#2]
i am using laravel 5.3 so it is not installing on my side.

can you please tell me its supported laravel 5.3 or not??

**Comment by solvercircle** [comment]
Hi,
It will need further development to integrate with Laravel 5.3

Thanks
Nasif

**Comment by amirgee007** [comment]
ok thank you but I need to use in my site I am trying other packages but they are not much efficient this is too good for me.

ok, i will wait for you to make compatible with newer version thanks to you for your reply.

I am watching the repo so that please update me when you update the support for a newer version.
